### PR TITLE
Added BoardConfig7420.mk

### PR DESCRIPTION
**Pull request by pnguyen879**
Added BoardConfig7420.mk

### CODE REVIEW

**Comment by ivanmeler** [comment]
Looks fine to me, does it work on s6/n5? if so ill merge it i have few 7420 devices i could test this on

**Comment by fakemanoan** [comment]
The repos require a bit of modification to properly support 7420. 
Gralloc needs a few modifications (assuming using r22p0 graphics driver, otherwise it gets a bit hectic). Relevant commits:
https://github.com/samsungexynos7420/android_hardware_samsung_slsi-linaro_exynos/commit/4730bf495b28a01b46b6222aed75b4df382481f6
https://github.com/samsungexynos7420/android_hardware_samsung_slsi-linaro_exynos/commit/f05a2a24cbe4ee038f0eaab89e2466c234f34304

OMX needs a small change to prevent error in compilation:
https://github.com/samsungexynos7420/android_hardware_samsung_slsi-linaro_openmax/commit/3b75e58518c730edcf5f2c4467c864e72954dd7f

hwc1 requires a change to properly support all layers (also relevant to 7580 I think):
https://github.com/samsungexynos7420/android_hardware_samsung_slsi-linaro_graphics/commit/b8f9a17fbb549fe7d6402221a80c0d1b39f68729
https://github.com/samsungexynos7420/android_hardware_samsung_slsi-linaro_graphics/commit/110d57c00743f5f7bb76a89199ac5d8fb3257fd8

These changes have been tested on S6, S6 edge, S6 edge+ and Note 5 without issues. Gralloc patches would need changing a bit to prevent it breaking 8890, but everything else should be fine

**Comment by pnguyen879** [comment]
I haven't tested it, is there a way I could test it somehow?
However, I believe it should work

**Comment by pnguyen879** [comment]
We could make a test repository to make sure it runs fast and good.

**Comment by pnguyen879** [comment]
it works

**Comment by pnguyen879** [comment]
definitely works just tested it

**Pull request closed without merging**
